version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - .:/app
      - /app/node_modules  # node_modules除外のための空ボリューム追加
    ports:
      - "3001:3001"
    environment:
      - PORT=3001

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8080:80"
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - ./public/videos:/usr/share/nginx/html/videos
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend